# Generated by Django 4.2.5 on 2024-03-19 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
